name: joltax_framework
description: Micro-framework for Flutter for that's built to simplify app development for Flutter projects.
version: 0.0.1+1
homepage: https://joltax.com
publisher: joltax.com
repository: https://github.com/joltax-core/framework/tree/0.x
issue_tracker: https://github.com/joltax-core/framework/issues
documentation: https://github.com/joltax-core/framework
funding:
  - https://github.com/sponsors/MBudak04
topics:
  - micro-framework
  - framework


environment:
  sdk: '>=3.6.0 <4.0.0' 
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

screenshots:
  - description: The Joltax package logo.
    path: screenshots/logo.png

flutter:

